---
title: "01_Preliminary_Analysis"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preliminary Analysis (FRT and t-tests)
Run an FRT to understand the causal effect of No Tillage (NT / treatment) vs. Conventional Tillage (CT / control) on crop yield, stratified by crop type.

## Load dataset
```{r load_data}
data <- read.csv('data/Database.csv')
data$Yield.Diff = data$Yield.of.NT -  data$Yield.of.CT
data$log.Yield.Ratio = log(data$Yield.of.NT) -  log(data$Yield.of.CT)
```

## Get list of unique crop types in the dataset
```{r all_crop_types}
crop_types = sort(unique(data$Crop))
```

## Define function to run an FRT
```{r def_FRT}
runFRT <- function(crop, n_iters) {
  
  # @param  crop      String-formatted name of crop from Crop column
  # @param  n_iters   Number of iterations to use for Fisher Randomization Test (FRT)
  # @return           P-value resulting from running FRT with n_iters iterations
  #                     using NT as treatment and CT as control
  
  cat('Running FRT for ',crop, '...')
  crop_subset = subset(data, Crop==crop)
  T_obs = mean(crop_subset$Yield.of.NT) - mean(crop_subset$Yield.of.CT)
  cat('\n\tT_obs: ', T_obs)
  
  T_FRT = vector(length=n_iters)
  for (i in 1:n_iters) {
    Z = sample(c(0,1),size=length(crop_subset),replace=TRUE) # PERMUTE RANDOMLY
    T_i = mean(c(crop_subset$Yield.of.NT[Z==1], crop_subset$Yield.of.CT[Z==0])) - 
        mean(c(crop_subset$Yield.of.NT[Z==0], crop_subset$Yield.of.CT[Z==1]))
    T_FRT[i] = T_i
  }

  if (T_obs > 0) {
   p_val = sum(T_FRT > T_obs) / length(T_FRT) 
  }
  else {
    p_val = sum(T_FRT < T_obs) / length(T_FRT)
  }
  cat('\n\tp-value: ', p_val, '\n')
  
  return (p_val)
  
}
```

## Run FRT for all crop types
```{r all_crop_FRTs}

# Generate a vector of p-values in the same order as crop_types

set.seed(100)
p_values = vector(length = length(crop_types))
n_iters = 10000

for (i in 1:length(crop_types)) {
  p_val = runFRT(crop_types[i], n_iters)
  p_values[i] = p_val
}

```

## Run t-test for all crop types
```{r all_crop_CLTs}

# Generate a vector of t-test results in the same order as crop_types

set.seed(42)

C = length(crop_types)

diff_in_yield_tau = vector(length=C)
diff_in_yield_p_vals = vector(length=C)
diff_in_yield_CI_lower = vector(length=C)
diff_in_yield_CI_upper = vector(length=C)

yield_ratio_tau = vector(length=C)
yield_ratio_p_vals = vector(length=C)
yield_ratio_CI_lower = vector(length=C)
yield_ratio_CI_upper = vector(length=C)

for (i in 1:length(crop_types)) {
    crop.msk = data$Crop == crop_types[i]
  
    yield_ratio_results = t.test(x = data$log.Yield.Ratio[crop.msk], mu = 0,
         paired =FALSE)
    yield_ratio_tau[i] = yield_ratio_results[[1]]
    yield_ratio_p_vals[i] = yield_ratio_results[[3]]
    yield_ratio_CI_lower[i] = yield_ratio_results[[4]][1]
    yield_ratio_CI_upper[i] = yield_ratio_results[[4]][2]
  
    diff_in_yield_results = t.test(x = log(data$Yield.of.NT)[crop.msk], y= log(data$Yield.of.CT)[crop.msk],
         paired =TRUE)
    diff_in_yield_tau[i] = diff_in_yield_results[[1]]
    diff_in_yield_p_vals[i] = diff_in_yield_results[[3]]
    diff_in_yield_CI_lower[i] = diff_in_yield_results[[4]][1]
    diff_in_yield_CI_upper[i] = diff_in_yield_results[[4]][2]
}

```


